FROM openjdk:17-jdk-slim
ARG JAR_FILE=target/ejercicio_duenio_mascotas-0.0.1.jar
COPY ${JAR_FILE} app_EjercicioDuenioMascotas.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app_EjercicioDuenioMascotas.jar"]